---
title: "Data Prep - Pacific Islands Trade"
author: "Avin Datt - PacifImpact"
date: "03 September 2020"
output: 
  github_document
---

# Scope  

Ingest IMTS Data into PostgreSQL database. 

# Reference

IMTS data is available in .xlsx format. It can be downloaded from [SPC Statistics for Development Division](https://sdd.spc.int/contact-us#disclaimer)

# Load Libraries 

```{r}
# Load openxlsx library 
if (!require(openxlsx)) {
  install.packages("openxlsx")
  library(openxlsx)
}

# Load purrr library
if (!require(purrr)) {
  install.packages("purrr")
  library(purrr)
}

# Load data.table library
if (!require(data.table)) {
  install.packages("data.table")
  library(data.table)
}
```

# Load Fiji Data 

Read in Balance of Trade - All Items for Fiji.

```{r}
# Read in Fiji File 
fj.imts.bot <- read.xlsx(xlsxFile = 'C:/Users/Avin/Documents/Data/Hackathon/AIS/ais-pacifimpact/data/external/Fiji_IMTS_Tables_2020.xlsx',
                         sheet = 1, 
                         startRow = 28,
                         skipEmptyCols = TRUE,
                         detectDates = TRUE,
                         rows = c(28:111),
                         cols = c(1:7))


```

Add and fix missing variable names. 

```{r}
# fj.imts.bot to data.table 
fj.imts.bot <- data.table(fj.imts.bot)


# Fix Monthly label to Year
setnames(fj.imts.bot, 
         "Monthly",
         "year")


# X2 should be Month 
setnames(fj.imts.bot, 
         "X2",
         "month")


# Exports FOB Domestic 
setnames(fj.imts.bot, 
         "X3",
         "exports-fob-domestic")


# Exports FOB Re-Export 
setnames(fj.imts.bot, 
         "X4",
         "exports-fob-reexport")


# Exports FOB Total 
setnames(fj.imts.bot, 
         "X5",
         "exports-fob-total")


# Imports CIF
setnames(fj.imts.bot, 
         "X6",
         "imports-cif")



# Trade Balance
setnames(fj.imts.bot, 
         "X7",
         "trade-balance")


```

Update Year values 

```{r}
# Update by using row number references
# 2014
fj.imts.bot[1:12, 
            year := 2014]


# 2015
fj.imts.bot[13:24, 
            year := 2015]


# 2016
fj.imts.bot[25:36, 
            year := 2016]


# 2017
fj.imts.bot[37:48, 
            year := 2017]


# 2018
fj.imts.bot[49:60, 
            year := 2018]


# 2019
fj.imts.bot[61:72, 
            year := 2019]


# 2020
fj.imts.bot[73:77, 
            year := 2020]


```


Melt data 

```{r}
# Melt the data to adhere to the schema design
fj.imts.bot <- melt.data.table(fj.imts.bot,
                               id = c("year",
                                      "month"), measure = c("exports-fob-domestic",
                                                            "exports-fob-reexport", 
                                                            "exports-fob-total",
                                                            "imports-cif",
                                                            "trade-balance"))
```




Add value properties. 

```{r}
# Add FJD 000 as property
fj.imts.bot[, 
            ]
```

