---
title: "Data Prep - Vanuatu AIS"
author: "Avin Datt - PacifImpact"
date: "04 September 2020"
output: 
  github_document
---

# Scope 

AIS data was acquired via UNGP but due to the fact cluster resources were scarce, AIS data had to be extracted from Spark and then stored in a database for the wider PacifImpact team to access. 

# Load Libraries

```{r load libs}
# Load data.table library
if (!require(data.table)) {
  install.packages("data.table")
  library(data.table)
}

# Load DBI library
if (!require(DBI)) {
  install.packages("DBI")
  library(DBI)
}

# Load DBI library
if (!require(RPostgres)) {
  install.packages("RPostgres")
  library(RPostgres)
}

```

# Read AIS Betio

Read the files extracted from UNGP for Betio, Kiribati. 

```{r}
# betio.v.list files
file.list <- list.files(path = "./data/external/ais_ki_betio/", 
                        pattern='*.csv')


# Read files in bulk
betio.v.list <- lapply(paste0("./data/external/ais_ki_betio/",
                           file.list),
                  fread)


# turn into one table 
betio.v.list <- rbindlist(betio.v.list)


betio.v.list <- betio.v.list[,1:28]


# Remove bad values that cause the write to db to fail
betio.v.list <- betio.v.list[!vessel_type_code %in% c("General Cargo Ship", "S-AIS", "TARAWA")]


# Change vessel_type_code to num type 
betio.v.list[,
             vessel_type_code := as.numeric(vessel_type_code)]


head(betio.v.list)
```

# Write AIS Betio to PostgreSQL

```{r eval=FALSE}
# Connect to a specific postgres database
db.con <- dbConnect(RPostgres::Postgres(),
                    dbname = 'aishackathon', 
                    host = 'ais-hack.cirquhp75zcc.us-east-2.rds.amazonaws.com', 
                    port = 5432, 
                    user = Sys.getenv("userid"),
                    password = Sys.getenv("pwd"))


# Append betio.v.list to country_metrics
RPostgres::dbWriteTable(db.con,
                        "stg_ais",
                        betio.v.list,
                        append = TRUE,
                        row.names = FALSE)


rm(betio.v.list)

```

